version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
