version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: 1404 

  app:
    image: golang
    working_dir: /app
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1404
    command: go run main.go

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80