version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  app:
    image: golang
    working_dir: /app
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: go run main.go

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80